server:
  port: 8085

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fooddelivery_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: payments
    show-sql: false
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
